spring.application.name=coreservices

#Postgresql Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d8nno4ok1i2s73dhlu0g-a.oregon-postgres.render.com:5432/ems_pzhn
spring.datasource.username=postgres_user
spring.datasource.password=AemcCY7CDxB3CkYF4UE853xWSXEET1od

#JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Port Number
server.port=8001