spring.application.name=coreservices

#Postgresql Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/mth
spring.datasource.url=jdbc:postgresql://dpg-d8kencsm0tmc73cjq500-a.oregon-postgres.render.com:5432/mth_75s0
spring.datasource.username=postgres_user
#spring.datasource.username=showkath
#spring.datasource.password=apoEwloBzaq4OADobaSa1YXYIi3mcr07
spring.datasource.password=apoEwloBzaq4OADobaSa1YXYIi3mcr07

#JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Port Number
server.port=8001